import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The sidebar follows the folders: docs/ (with _category_.json in each).
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
