//! The `docker` runtime (M0.8, D-02, DEC-112): the lane's nodes as
//! containers from the release's images, run with Docker Compose, on this
//! machine (`local`) or on a host over ssh. The host keeps the same layout as
//! the other runtimes (`config/`, `keys/`, `data/`, `run/`), plus the
//! rendered `config/compose.yml` and, with a public URL, `config/Caddyfile`
//! for the `web` container. Plan, fingerprints and restarts are the same as
//! for processes and systemd units: `run/<node>.started` holds the configs a
//! node was started with.
//!
//! Every operation is one shell script, run here or on the host. On an ssh
//! host the files belong to uid 10001, the containers' user, and the scripts
//! use `sudo`; here they belong to you, and the containers run as you.

use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

use anyhow::{anyhow, bail, Context, Result};

use crate::manifest::{Manifest, Provider};
use crate::plan::{Host, Key, NodeReport, NodeState};
use crate::release::Release;
use crate::render::{validator_node, validator_port};
use crate::ssh::Ssh;

enum Via {
    Here,
    Ssh(Box<Ssh>),
}

pub struct Docker {
    pub root: String,
    via: Via,
    template: String,
    project: String,
    /// Where this machine keeps the lane's exported proofs.
    local_dir: PathBuf,
    /// Its name in the deployment.
    host: String,
}

fn q(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

fn hex(k: &[u8]) -> String {
    k.iter().map(|b| format!("{b:02x}")).collect()
}

fn hex_key(s: &str) -> Option<Key> {
    let v: Vec<u8> = (0..32)
        .map(|i| u8::from_str_radix(s.get(2 * i..2 * i + 2)?, 16).ok())
        .collect::<Option<_>>()?;
    v.try_into().ok()
}

/// `# Generated by caravel from lane "<name>", [env.<env>]…`.
fn owner(header: &str) -> Option<(String, String)> {
    let rest = header.split_once("from lane ")?.1;
    let (lane, rest) = rest.strip_prefix('"')?.split_once('"')?;
    let env = rest.split_once("[env.")?.1.split_once(']')?.0;
    Some((lane.to_string(), env.to_string()))
}

/// The release step's image commands: pull (or check) each image this lane
/// runs, then remove the older images of the lane's own repositories (D-20).
/// Docker refuses to remove an image a container still uses, running or
/// stopped, so the release the nodes run until their restart stays: after a
/// deploy the host keeps this release and the one before it, the rollback
/// target. Only registry refs by digest are pruned (never a local build's
/// tags), and never `caddy`, a shared upstream image.
fn image_lines(d: &str, template: &str, images: &BTreeMap<String, String>) -> String {
    let mut script = String::new();
    let mut prune = String::new();
    for (role, image) in images {
        let own = role == &format!("{template}-node")
            || role == &format!("{template}-web")
            || role == "relayer";
        if !own && role != "caddy" {
            continue;
        }
        if !pullable(image) {
            script += &format!(
                "{d} image inspect {i} >/dev/null 2>&1 || {{ echo 'no local image {image}: build it with scripts/build-images.sh' >&2; exit 1; }}\n",
                i = q(image)
            );
            continue;
        }
        script += &format!("{d} pull -q {} >/dev/null\n", q(image));
        if let (true, Some((repo, _))) = (own, image.split_once('@')) {
            prune += &format!(
                "keep=$({d} image inspect -f '{{{{.Id}}}}' {i}); for id in $({d} images -q --no-trunc {r} | sort -u); do [ \"$id\" = \"$keep\" ] || {d} image rm \"$id\" >/dev/null 2>&1 || true; done\n",
                i = q(image),
                r = q(repo)
            );
        }
    }
    script + &prune
}

/// An image ref that names a registry (pullable), not a local build's tag.
fn pullable(image: &str) -> bool {
    image.contains('@')
        || image
            .split_once('/')
            .is_some_and(|(r, _)| r.contains('.') || r.contains(':') || r == "localhost")
}

impl Docker {
    /// Host `host` of the deployment.
    pub fn named(m: &Manifest, template: &str, state_root: &Path, host: &str) -> Result<Self> {
        let spec = m.env.host_spec(host).clone();
        let project = spec.compose_project(&m.lane.lane.name, &m.env_name);
        let (root, via, local_dir) = match spec.provider {
            Provider::Local => {
                let l = crate::local::Local::named(m, template, state_root, host)?;
                (l.root_str(), Via::Here, l.root.clone())
            }
            Provider::Ssh => {
                let s = Ssh::named(m, template, state_root, host)?;
                (
                    s.root.clone(),
                    Via::Ssh(Box::new(Ssh::named(m, template, state_root, host)?)),
                    s.local_dir,
                )
            }
        };
        Ok(Self {
            root,
            via,
            template: template.to_string(),
            project,
            local_dir,
            host: host.to_string(),
        })
    }

    pub fn exit_path(&self) -> PathBuf {
        self.local_dir.join("exit.json")
    }

    fn remote(&self) -> bool {
        matches!(self.via, Via::Ssh(_))
    }

    /// `sudo ` on an ssh host, where the files are uid 10001's.
    fn s(&self) -> &'static str {
        if self.remote() {
            "sudo "
        } else {
            ""
        }
    }

    /// `install`'s owner flags: the containers' user on an ssh host.
    fn own(&self) -> &'static str {
        if self.remote() {
            "-o 10001 -g 10001 "
        } else {
            ""
        }
    }

    /// A shell command that writes stdin to `dest` with `mode`: `install` on
    /// an ssh host (owned by the containers' user); here, `cat` (BSD
    /// `install`, on macOS, can't read stdin).
    fn put(&self, dest: &str, mode: &str) -> String {
        if self.remote() {
            format!("sudo install -o 10001 -g 10001 -m {mode} /dev/stdin {dest}")
        } else {
            format!("{{ umask 077; cat > {dest}; }} && chmod {mode} {dest}")
        }
    }

    /// Docker Compose on the lane's file; here, the containers run as you.
    fn compose(&self) -> String {
        let f = q(&format!("{}/config/compose.yml", self.root));
        if self.remote() {
            format!("sudo docker compose -f {f}")
        } else {
            format!("CARAVEL_UID=$(id -u) CARAVEL_GID=$(id -g) docker compose -f {f}")
        }
    }

    fn docker(&self) -> &'static str {
        if self.remote() {
            "sudo docker"
        } else {
            "docker"
        }
    }

    pub fn exec(&self, script: &str, stdin: &[u8]) -> Result<String> {
        match &self.via {
            Via::Ssh(s) => s.exec(script, stdin),
            Via::Here => {
                let mut child = Command::new("bash")
                    .arg("-c")
                    .arg(script)
                    .stdin(Stdio::piped())
                    .stdout(Stdio::piped())
                    .stderr(Stdio::piped())
                    .spawn()
                    .context("running bash")?;
                child.stdin.take().expect("piped").write_all(stdin)?;
                let out = child.wait_with_output()?;
                if !out.status.success() {
                    let err = String::from_utf8_lossy(&out.stderr).trim().to_string();
                    bail!(
                        "{}",
                        if err.is_empty() {
                            format!("a host script exited with {}", out.status)
                        } else {
                            err
                        }
                    );
                }
                Ok(String::from_utf8_lossy(&out.stdout).into_owned())
            }
        }
    }

    /// Runs `script` with this terminal's output (logs).
    fn interactive(&self, script: &str) -> Result<()> {
        let status = match &self.via {
            Via::Ssh(s) => s.remote_command(script).stdin(Stdio::null()).status(),
            Via::Here => Command::new("bash")
                .arg("-c")
                .arg(script)
                .stdin(Stdio::null())
                .status(),
        }
        .context("running docker compose")?;
        if !status.success() {
            bail!("docker compose logs failed ({status})");
        }
        Ok(())
    }

    /// What the host has, from one script.
    pub async fn read(&self, m: &Manifest) -> Result<Host> {
        let r = q(&self.root);
        let s = self.s();
        let d = self.docker();
        let mut ports = vec![("sequencer".to_string(), m.env.sequencer.port)];
        for (i, v) in m.env.run_validators() {
            ports.push((validator_node(&v.name), validator_port(m, i)));
        }
        let mut script = format!(
            "R={r}\n\
             command -v docker >/dev/null || echo 'MISSING docker'\n\
             {d} compose version >/dev/null 2>&1 || echo 'MISSING the Docker Compose plugin (docker compose)'\n\
             {d} info >/dev/null 2>&1 || echo 'MISSING a running Docker daemon you can use'\n"
        );
        if self.remote() {
            script += "sudo -n true 2>/dev/null || echo 'MISSING passwordless sudo'\n";
        }
        script += &format!(
            "echo \"COMMIT $({s}cat $R/COMMIT 2>/dev/null | cut -c1-12)\"\n\
             for f in $R/config/*; do [ -f \"$f\" ] && echo \"FILE $(basename $f) $({s}cat $f | (sha256sum 2>/dev/null || shasum -a 256) | cut -c1-64)\"; done\n\
             for f in $R/run/*.started; do [ -f \"$f\" ] && echo \"STARTED $(basename $f .started) $({s}cat $f)\"; done\n\
             {s}sh -c \"ls $R/data/*.sqlite\" >/dev/null 2>&1 && echo DATA\n\
             [ -f $R/config/lane.toml ] && echo \"OWNER $({s}head -1 $R/config/lane.toml)\"\n\
             {d} ps -a --filter label=com.docker.compose.project={p} --format '{{{{.Label \"com.docker.compose.service\"}}}} {{{{.State}}}}' 2>/dev/null | sed 's/^/CTR /'\n",
            p = q(&self.project),
        );
        for (n, port) in &ports {
            script += &format!(
                "echo \"STATUS {n} $(curl -sf -m 3 http://127.0.0.1:{port}/v1/status | tr -d '\\n')\"\n\
                 (exec 3<>/dev/tcp/127.0.0.1/{port}) 2>/dev/null && echo \"LISTEN {n} {port}\"\n"
            );
        }
        script += "true\n";
        let out = self.exec(&script, b"")?;
        let mut host = Host::default();
        let mut containers = std::collections::BTreeSet::new();
        for line in out.lines() {
            let (tag, rest) = line.split_once(' ').unwrap_or((line, ""));
            match tag {
                "MISSING" => host.missing.push(rest.to_string()),
                "COMMIT" if !rest.trim().is_empty() => host.release = Some(rest.trim().to_string()),
                "FILE" => {
                    if let Some((name, h)) = rest.split_once(' ') {
                        if let Some(k) = hex_key(h.trim()) {
                            host.files.insert(name.to_string(), k);
                        }
                    }
                }
                "STARTED" => {
                    if let Some((node, h)) = rest.split_once(' ') {
                        host.nodes.entry(node.to_string()).or_default().started_with =
                            hex_key(h.trim());
                    }
                }
                "DATA" => host.has_data = true,
                "OWNER" => {
                    if let Some((lane, env)) = owner(rest) {
                        if lane != m.lane.lane.name || env != m.env_name {
                            host.taken =
                                Some(format!("{} holds lane {lane:?} [env.{env}]", self.root));
                        }
                    }
                }
                "CTR" => {
                    if let Some((service, state)) = rest.split_once(' ') {
                        if service != "web" {
                            containers.insert(service.to_string());
                            host.nodes.entry(service.to_string()).or_default().running =
                                state.trim() == "running";
                        }
                    }
                }
                "LISTEN" => {
                    if let Some((node, port)) = rest.split_once(' ') {
                        if let Ok(port) = port.trim().parse() {
                            host.listening.insert(node.to_string(), port);
                        }
                    }
                }
                "STATUS" => {
                    if let Some((node, json)) = rest.split_once(' ') {
                        if let Ok(v) = serde_json::from_str::<serde_json::Value>(json) {
                            host.nodes.entry(node.to_string()).or_default().report =
                                crate::local::node_report(&v);
                        }
                    }
                }
                _ => {}
            }
        }
        // A node with a fingerprint or status but no container isn't running.
        host.nodes.retain(|n, st: &mut NodeState| {
            containers.contains(n) || st.started_with.is_some() || st.report.is_some()
        });
        Ok(host)
    }

    /// The release on a docker host is its images: pull the ones this lane
    /// runs (a local build's are checked instead), and record the commit.
    pub fn install_release(&self, r: &Release) -> Result<()> {
        if r.images.is_empty() {
            bail!("the release has no images (no IMAGES file): build them with scripts/build-images.sh, or use a release from CI");
        }
        let d = self.docker();
        let mut script = format!(
            "set -e; R={r}\n{s}install -d {own}-m 755 $R $R/config $R/caddy $R/caddy/data $R/caddy/config\n{s}install -d {own}-m 700 $R/keys $R/data $R/run\n",
            r = q(&self.root),
            s = self.s(),
            own = self.own(),
        );
        script += &image_lines(d, &self.template, &r.images);
        script += &format!(
            "echo {} | {put}\n",
            q(&r.commit),
            put = self.put("$R/COMMIT", "644")
        );
        self.exec(&script, b"").map(|_| ())
    }

    /// Writes a rendered file under `config/`. The web container reads the
    /// Caddyfile and the compose file names its image, so it follows them.
    pub fn write_file(&self, name: &str, text: &str) -> Result<()> {
        let r = q(&self.root);
        let s = self.s();
        let own = self.own();
        let mut script = format!(
            "set -e; R={r}; {s}install -d {own}-m 755 $R/config $R/caddy $R/caddy/data $R/caddy/config; {put}\n",
            put = self.put(&format!("$R/config/{}", q(name)), "644")
        );
        let c = self.compose();
        if name == "Caddyfile" {
            script += &format!("if [ -f $R/config/compose.yml ] && grep -q '^  web:' $R/config/compose.yml; then {c} restart web >/dev/null 2>&1 || {c} up -d --no-deps web >/dev/null; fi\n");
        } else if name == "compose.yml" {
            script += &format!("if grep -q '^  web:' $R/config/compose.yml; then {c} up -d --no-deps web >/dev/null; fi\n");
        }
        self.exec(&script, text.as_bytes()).map(|_| ())
    }

    /// The validators' keys and the env file, over stdin into mode-600 files
    /// the containers' user owns; the internal token is made once and kept.
    pub fn write_keys(
        &self,
        validators: &[(String, String)],
        env: &[(String, String)],
    ) -> Result<()> {
        let r = q(&self.root);
        let s = self.s();
        let own = self.own();
        self.exec(
            &format!("{s}install -d {own}-m 700 {r}/keys {r}/data {r}/run"),
            b"",
        )?;
        for (node, secret) in validators {
            self.exec(
                &self.put(&format!("{r}/keys/{}", q(&format!("{node}.key"))), "600"),
                format!("{secret}\n").as_bytes(),
            )?;
        }
        let keep: String = validators
            .iter()
            .map(|(node, _)| format!(" ! -name {}", q(&format!("{node}.key"))))
            .collect();
        self.exec(
            &format!("{s}find {r}/keys -maxdepth 1 -name 'validator-*.key'{keep} -delete"),
            b"",
        )?;
        let body: String = env.iter().map(|(k, v)| format!("{k}={v}\n")).collect();
        self.exec(
            &format!(
                "set -e; T=$({s}sed -n 's/^CARAVEL_INTERNAL_TOKEN=//p' {r}/keys/env 2>/dev/null || true)\n\
                 [ -n \"$T\" ] || T=$(openssl rand -hex 24)\n\
                 {{ echo \"CARAVEL_INTERNAL_TOKEN=$T\"; cat; }} | {put}",
                put = self.put(&format!("{r}/keys/env"), "600")
            ),
            body.as_bytes(),
        )
        .map(|_| ())
    }

    /// (Re)creates a node's container and records the configs it read.
    pub fn start(&self, node: &str, fingerprint: &Key) -> Result<()> {
        self.exec(
            &format!(
                "set -e; {c} up -d --no-deps --force-recreate {n} >/dev/null 2>&1 || {c} up -d --no-deps --force-recreate {n}\necho {fp} | {put}",
                c = self.compose(),
                n = q(node),
                fp = hex(fingerprint),
                put = self.put(&format!("{}/run/{}", q(&self.root), q(&format!("{node}.started"))), "644"),
            ),
            b"",
        )
        .map(|_| ())
    }

    /// Removes a node's container, also one the compose file no longer names.
    pub fn stop(&self, node: &str) -> Result<()> {
        self.exec(
            &format!(
                "ids=$({d} ps -aq --filter label=com.docker.compose.project={p} --filter label=com.docker.compose.service={n}); [ -z \"$ids\" ] || {d} rm -f $ids >/dev/null; {s}rm -f {r}/run/{f}",
                d = self.docker(),
                p = q(&self.project),
                n = q(node),
                s = self.s(),
                r = q(&self.root),
                f = q(&format!("{node}.started")),
            ),
            b"",
        )
        .map(|_| ())
    }

    pub fn wipe(&self, nodes: &[String]) -> Result<()> {
        for n in nodes {
            self.stop(n)?;
        }
        self.stop("web")?;
        self.exec(
            &format!("{}sh -c 'rm -rf -- {}/data/*'", self.s(), self.root),
            b"",
        )
        .map(|_| ())
    }

    /// `export-proofs` in a one-off container of the validator's image.
    pub fn export_proofs(&self, node: &str, out: &Path) -> Result<()> {
        let json = self.exec(
            &format!(
                "{c} run --rm --no-deps -T {n} export-proofs --config {cfg}",
                c = self.compose(),
                n = q(node),
                cfg = q(&format!("{}/config/{node}.toml", crate::render::RUN_ROOT)),
            ),
            b"",
        )?;
        if let Some(dir) = out.parent() {
            std::fs::create_dir_all(dir)?;
        }
        std::fs::write(out, json)?;
        Ok(())
    }

    pub fn read_file(&self, name: &str) -> Result<Option<String>> {
        let p = q(&format!("{}/config/{name}", self.root));
        let out = self.exec(
            &format!(
                "{s}test -f {p} && {{ echo EXISTS; {s}cat {p}; }} || true",
                s = self.s()
            ),
            b"",
        )?;
        Ok(out.strip_prefix("EXISTS\n").map(str::to_string))
    }

    /// A node's `/v1/status` at the port the host publishes on loopback.
    pub async fn status(&self, port: u16) -> Option<serde_json::Value> {
        let out = self
            .exec(
                &format!("curl -sf -m 3 http://127.0.0.1:{port}/v1/status"),
                b"",
            )
            .ok()?;
        serde_json::from_str(&out).ok()
    }

    pub fn logs(&self, node: &str, lines: usize, follow: bool) -> Result<()> {
        self.interactive(&format!(
            "{} logs --no-log-prefix -n {lines}{} {}",
            self.compose(),
            if follow { " -f" } else { "" },
            q(node)
        ))
    }

    pub fn log_tail(&self, node: &str) -> String {
        self.exec(
            &format!(
                "{} logs --no-log-prefix -n 8 {} 2>&1",
                self.compose(),
                q(node)
            ),
            b"",
        )
        .unwrap_or_default()
    }

    /// Waits until the node on `port` reports `want`.
    pub async fn wait_healthy(
        &self,
        port: u16,
        want: &NodeReport,
        timeout: Duration,
    ) -> Result<()> {
        let deadline = Instant::now() + timeout;
        let mut last = "no answer".to_string();
        while Instant::now() < deadline {
            if let Some(v) = self.status(port).await {
                match crate::local::node_report(&v) {
                    Some(r) if want.key.is_some() && r.key != want.key => {
                        last = "another validator answers on its port".into()
                    }
                    Some(r)
                        if r.lane_id == want.lane_id
                            && r.config_hash == want.config_hash
                            && r.settlement == want.settlement
                            && r.engine_wasm_hash == want.engine_wasm_hash =>
                    {
                        return Ok(())
                    }
                    Some(_) => last = "it runs another lane, config, settlement or engine".into(),
                    None => {
                        last = "its status lacks the identity fields (an older release?)".into()
                    }
                }
            }
            tokio::time::sleep(Duration::from_millis(if self.remote() {
                2000
            } else {
                500
            }))
            .await;
        }
        Err(anyhow!(
            "{} on port {port} of host {} is not healthy: {last}",
            self.project,
            self.host
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_release_pulls_its_images_and_prunes_only_its_own_older_ones() {
        let node = "ghcr.io/wmendes/caravel-perps-node@sha256:aa";
        let images = BTreeMap::from([
            ("perps-node".to_string(), node.to_string()),
            (
                "relayer".to_string(),
                "ghcr.io/wmendes/caravel-relayer@sha256:bb".to_string(),
            ),
            (
                "perps-web".to_string(),
                "caravel-perps-web:local-1".to_string(),
            ),
            (
                "caddy".to_string(),
                "docker.io/library/caddy:2.11.6@sha256:cc".to_string(),
            ),
            (
                "payments-node".to_string(),
                "ghcr.io/wmendes/caravel-payments-node@sha256:dd".to_string(),
            ),
        ]);
        let s = image_lines("sudo docker", "perps", &images);
        // Every image this lane runs is pulled, or checked when it is local.
        for i in [
            node,
            "ghcr.io/wmendes/caravel-relayer@sha256:bb",
            "docker.io/library/caddy:2.11.6@sha256:cc",
        ] {
            assert!(s.contains(&format!("sudo docker pull -q {}", q(i))), "{s}");
        }
        assert!(
            s.contains(&format!(
                "image inspect {} >/dev/null",
                q("caravel-perps-web:local-1")
            )),
            "{s}"
        );
        // Older images go for the node and the relayer, each keeping its own digest.
        assert!(
            s.contains(&format!(
                "keep=$(sudo docker image inspect -f '{{{{.Id}}}}' {})",
                q(node)
            )),
            "{s}"
        );
        assert!(
            s.contains(&format!(
                "images -q --no-trunc {}",
                q("ghcr.io/wmendes/caravel-perps-node")
            )),
            "{s}"
        );
        assert!(
            s.contains(&format!(
                "images -q --no-trunc {}",
                q("ghcr.io/wmendes/caravel-relayer")
            )),
            "{s}"
        );
        // Never a local build, caddy, or another template's repository.
        assert!(!s.contains("--no-trunc 'caravel-perps-web"), "{s}");
        assert!(
            !s.contains(&format!("--no-trunc {}", q("docker.io/library/caddy"))),
            "{s}"
        );
        assert!(!s.contains("caravel-payments-node"), "{s}");
        // The prune comes after every pull, and can't fail the step.
        let last_pull = s.rfind(" pull -q ").unwrap();
        assert!(s.find("keep=").unwrap() > last_pull, "{s}");
        assert!(
            s.lines()
                .filter(|l| l.starts_with("keep="))
                .all(|l| l.ends_with("|| true; done")),
            "{s}"
        );
    }

    #[test]
    fn registry_refs_are_pulled_local_tags_are_not() {
        assert!(pullable("ghcr.io/wmendes/caravel-perps-node@sha256:ab"));
        assert!(pullable("docker.io/library/caddy:2.11.6@sha256:ab"));
        assert!(pullable("localhost:5000/caravel-relayer:x"));
        assert!(!pullable("caravel-perps-node:local-1234"));
        assert_eq!(
            owner("# Generated by caravel from lane \"pay\", [env.dev]; …"),
            Some(("pay".into(), "dev".into()))
        );
    }
}
