//! The node configs a deployment gives, as files under the host's root:
//!
//! ```text
//! <root>/config/lane.toml            the lane file without [env]
//! <root>/config/sequencer.toml
//! <root>/config/validator-<name>.toml
//! <root>/config/relayer.json
//! <root>/keys/                       validator keys and the env file (never rendered here)
//! <root>/data/                       stores
//! <root>/{bin,contracts,relayer,relayer-feeds}/   the release
//! ```
//!
//! Paths are absolute, so a config means the same thing wherever it is read.
//! On a docker host (D-02) the configs name the root the containers mount,
//! `/opt/caravel`, and the host keeps the files under its own root, beside a
//! `compose.yml` and, with a public URL, the `Caddyfile` its web container
//! reads.
//! No secret is in any of these files: keys are files under `keys/`, and the
//! sequencer and relayer read theirs from the environment.

use std::collections::BTreeMap;

use anyhow::Result;
use serde_json::json;

use crate::address::strkey;
use crate::manifest::{Manifest, Provider, Runtime};
use crate::plan::Key;

/// What rendering needs besides the lane file: keys and hashes, resolved.
#[derive(Clone, Debug)]
pub struct Resolved {
    pub template: String,
    pub engine_wasm_hash: Key,
    pub settlement: Key,
    /// Each validator's public key, in file order.
    pub validator_keys: Vec<Key>,
    /// The release has a web app to serve at the public URL.
    pub web: bool,
    /// The sequencer's request key (`[sequencer] key`, DEC-095).
    pub sequencer_key: Option<Key>,
    /// The release's images by role (`IMAGES`, DEC-111), for docker hosts.
    pub images: BTreeMap<String, String>,
}

/// Where a docker host's containers see the lane's root (D-02).
pub const RUN_ROOT: &str = "/opt/caravel";

/// An RPC URL as a container reaches it: a network on the host's loopback
/// (the local network) is `host.docker.internal`, which the compose file
/// maps to the host on Linux too.
pub fn container_url(url: &str) -> String {
    for lo in ["://localhost", "://127.0.0.1"] {
        if let Some(i) = url.find(lo) {
            return format!(
                "{}://host.docker.internal{}",
                &url[..i],
                &url[i + lo.len()..]
            );
        }
    }
    url.to_string()
}

pub fn g(k: &Key) -> String {
    stellar_strkey::ed25519::PublicKey(*k)
        .to_string()
        .as_str()
        .to_string()
}

fn hex(k: &[u8]) -> String {
    k.iter().map(|b| format!("{b:02x}")).collect()
}

/// A TOML string literal.
fn q(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

fn list(items: &[String]) -> String {
    format!(
        "[{}]",
        items.iter().map(|s| q(s)).collect::<Vec<_>>().join(", ")
    )
}

/// `<template>_engine.wasm`, as `scripts/build-contracts.sh` names it.
pub fn engine_file(template: &str) -> String {
    format!("{template}_engine.wasm")
}

/// `validator-<name>`.
pub fn validator_node(name: &str) -> String {
    format!("validator-{name}")
}

/// Every generated file of the sequencer's host, by its path under
/// `<root>/config/`.
pub fn render(
    m: &Manifest,
    r: &Resolved,
    root: &str,
    epoch: u64,
) -> Result<BTreeMap<String, String>> {
    render_for(m, r, &m.env.primary_host(), root, epoch)
}

/// Every generated file of `host` (C-22): the lane file, its own nodes'
/// configs and, on an ssh host, their units and its Caddyfile. A node
/// another host calls listens on that host's private address.
pub fn render_for(
    m: &Manifest,
    r: &Resolved,
    host: &str,
    root: &str,
    epoch: u64,
) -> Result<BTreeMap<String, String>> {
    let e = &m.env;
    let primary = e.primary_host();
    let docker = e.host_spec(host).runtime() == Runtime::Docker;
    // The host's root, where the files are; the configs name the root their
    // nodes see, which in a container is RUN_ROOT.
    let host_root = root;
    let root = if docker { RUN_ROOT } else { root };
    let passphrase = e.network.passphrase();
    let rpc = if docker {
        container_url(m.rpc_url())
    } else {
        m.rpc_url().to_string()
    };
    let settlement = strkey(&r.settlement);
    let engine = format!("{root}/contracts/{}", engine_file(&r.template));
    let engine_hash = hex(&r.engine_wasm_hash);
    let lane = format!("{root}/config/lane.toml");
    // The sequencer, as the relayer beside it reaches it.
    let seq_listen = e.listen_on(&primary, "sequencer");
    let seq_url = e
        .url_of(&primary, "sequencer")
        .unwrap_or_else(|| format!("http://{seq_listen}:{}", e.sequencer.port));
    let loopback = |port: u16| format!("http://127.0.0.1:{port}");
    let mut out = BTreeMap::new();

    out.insert(
        "lane.toml".to_string(),
        format!(
            "# Generated by caravel from lane {:?}, [env.{}]; the deployment tables are left out.\n{}",
            m.lane.lane.name,
            m.env_name,
            toml::to_string(&m.lane.raw)?
        ),
    );

    let here = |node: &str| e.host_of(node) == host;
    let mut seq = format!(
        "# Generated by caravel ([env.{env}]). CARAVEL_INTERNAL_TOKEN comes from the environment.\n\
         [sequencer]\n\
         listen = {listen}\n\
         lane = {lane}\n\
         engine_wasm = {engine}\n\
         engine_wasm_sha256 = {hash}\n\
         db = {db}\n\
         network_passphrase = {pass}\n\
         settlement_contract = {settlement}\n\
         internal_token_env = \"CARAVEL_INTERNAL_TOKEN\"\n\
         executor = \"wasm\"\n\
         production = {production}\n",
        env = m.env_name,
        listen = q(&format!("{seq_listen}:{}", e.sequencer.port)),
        lane = q(&lane),
        engine = q(&engine),
        hash = q(&engine_hash),
        db = q(&format!("{root}/data/sequencer.sqlite")),
        pass = q(passphrase),
        settlement = q(&settlement),
        production = e.sequencer.production,
    );
    if !e.sequencer.cors_origins.is_empty() {
        seq += &format!("cors_origins = {}\n", list(&e.sequencer.cors_origins));
    }
    if r.sequencer_key.is_some() {
        seq += &format!("key_file = {}\n", q(&format!("{root}/keys/sequencer.key")));
    }
    seq += &format!(
        "\n[signers]\nepoch = {epoch}\nthreshold = {}\nvalidators = [\n",
        e.threshold
    );
    for (v, k) in e.validators.iter().zip(&r.validator_keys) {
        // The manifest checked that the sequencer reaches each one.
        let url = e
            .url_of(&primary, &validator_node(&v.name))
            .unwrap_or_default();
        seq += &format!(
            "  {{ url = {}, key = {}, weight = {} }},\n",
            q(&url),
            q(&g(k)),
            v.weight
        );
    }
    seq += "]\n";
    if host == primary {
        out.insert("sequencer.toml".to_string(), seq);
    }

    for (i, v) in e.run_validators() {
        let node = validator_node(&v.name);
        if !here(&node) {
            continue;
        }
        let seq_url = e
            .url_of(host, "sequencer")
            .unwrap_or_else(|| loopback(e.sequencer.port));
        let mut t = format!(
            "# Generated by caravel ([env.{env}]). The key is in key_file.\n\
             [validator]\n\
             listen = {listen}\n\
             sequencer_url = {seq_url}\n\
             key_file = {key}\n\
             lane = {lane}\n\
             engine_wasm = {engine}\n\
             engine_wasm_sha256 = {hash}\n\
             db = {db}\n\
             network_passphrase = {pass}\n\
             settlement_contract = {settlement}\n\
             rpc_url = {rpc}\n\
             poll_ms = {poll}\n\
             stellar_poll_secs = {stellar}\n",
            env = m.env_name,
            listen = q(&format!(
                "{}:{}",
                e.listen_on(host, &node),
                validator_port(m, i)
            )),
            seq_url = q(&seq_url),
            key = q(&format!("{root}/keys/{node}.key")),
            lane = q(&lane),
            engine = q(&engine),
            hash = q(&engine_hash),
            db = q(&format!("{root}/data/{node}.sqlite")),
            pass = q(passphrase),
            settlement = q(&settlement),
            rpc = q(&rpc),
            poll = e.validator_polling.sequencer_ms,
            stellar = e.validator_polling.stellar_secs,
        );
        if !e.sequencer.cors_origins.is_empty() {
            t += &format!("cors_origins = {}\n", list(&e.sequencer.cors_origins));
        }
        if let Some(k) = &r.sequencer_key {
            t += &format!("sequencer_key = {}\n", q(&g(k)));
        }
        out.insert(format!("{node}.toml"), t);
    }

    let feeds: Vec<serde_json::Value> = e
        .relayer
        .feeds
        .iter()
        .map(|f| {
            let mut v = serde_json::to_value(f)?;
            if let Some(module) = v["module"].as_str() {
                if !module.starts_with('/') {
                    v["module"] = json!(format!("{root}/{module}"));
                }
            }
            Ok(v)
        })
        .collect::<Result<_>>()?;
    let mut relayer = json!({
        "rpcUrl": rpc,
        "networkPassphrase": passphrase,
        "settlementContract": settlement,
        "sequencerUrl": seq_url,
        "metricsFile": format!("{root}/data/relayer-checkpoints.jsonl"),
        "loops": { "inbox": true, "checkpoints": true },
        "feeds": feeds,
    });
    if let Some(i) = &e.relayer.intervals_ms {
        relayer["intervalsMs"] = serde_json::to_value(i)?;
    }
    if host == primary {
        out.insert(
            "relayer.json".to_string(),
            serde_json::to_string_pretty(&relayer)? + "\n",
        );
    }
    // The web app's config, on the host that serves it (C-25).
    if let Some(w) = e
        .web
        .as_ref()
        .filter(|_| e.web_host().as_deref() == Some(host))
    {
        out.insert(
            "web.json".to_string(),
            serde_json::to_string_pretty(&serde_json::to_value(&w.config)?)? + "\n",
        );
    }
    if docker {
        out.extend(docker_files(m, r, host, host_root)?);
    } else if m.env.host_spec(host).provider == Provider::Ssh {
        out.extend(host_files(m, r, host, root));
    }
    Ok(out)
}

/// Caddy's route to the web app's config (C-25): `/config.json` is
/// `<root>/config/web.json`, and nothing else of that directory.
fn web_config_route(root: &str) -> String {
    format!("\thandle /config.json {{\n\t\troot * {root}/config\n\t\trewrite * /web.json\n\t\tfile_server\n\t}}\n")
}

/// The web app itself, from the release.
fn web_route(root: &str) -> String {
    format!("\thandle {{\n\t\troot * {root}/web\n\t\ttry_files {{path}} /index.html\n\t\tfile_server\n\t}}\n")
}

/// A systemd service for a node, as lane #1's VM has them (DEC-046).
fn unit(
    description: &str,
    after: &str,
    env_file: bool,
    workdir: Option<&str>,
    exec: &str,
    root: &str,
) -> String {
    let mut s = format!(
        "[Unit]\nDescription={description}\nAfter=network-online.target{after}\nWants=network-online.target\n\n[Service]\nUser=caravel\nGroup=caravel\n"
    );
    if env_file {
        s += &format!("EnvironmentFile={root}/keys/env\n");
    }
    if workdir.is_none() {
        s += "Environment=RUST_LOG=info\n";
    }
    if let Some(w) = workdir {
        s += &format!("WorkingDirectory={w}\n");
    }
    s += &format!(
        "ExecStart={exec}\nRestart=on-failure\nRestartSec=5\nNoNewPrivileges=true\nProtectSystem=strict\nProtectHome=true\nPrivateTmp=true\nReadWritePaths={root}/data\n\n[Install]\nWantedBy=multi-user.target\n"
    );
    s
}

/// An ssh host's systemd units for the nodes it runs and, with a public
/// URL, its Caddyfile; keyed `systemd/<unit>` and `caddy/Caddyfile`.
fn host_files(m: &Manifest, r: &Resolved, host: &str, root: &str) -> BTreeMap<String, String> {
    let e = &m.env;
    let primary = e.primary_host() == host;
    let mine: Vec<(usize, &crate::manifest::ValidatorSpec)> = e
        .run_validators()
        .filter(|(_, v)| e.host_of(&validator_node(&v.name)) == host)
        .collect();
    let net = m.env.network.name();
    let bin = format!("{root}/bin/{}", crate::release::node_binary(&r.template));
    // A namespace's units and Caddy snippet (C-24); without one, the names
    // of a host with one lane.
    let spec = e.host_spec(host);
    let pre = spec.unit_prefix();
    let caddy = spec.caddy_file();
    let web_here = e.web_host().as_deref() == Some(host);
    let mut out = BTreeMap::new();
    if !primary {
        // Only validators here: their unit, and their public API.
        if !mine.is_empty() {
            out.insert(
                format!("systemd/{pre}validator@.service"),
                unit(
                    &format!("Caravel validator %i ({net})"),
                    "",
                    false,
                    None,
                    &format!("{bin} validator --config {root}/config/validator-%i.toml"),
                    root,
                ),
            );
        }
        if let Some(name) = e.host_spec(host).public_url.as_deref().map(|u| {
            u.trim_start_matches("https://")
                .trim_start_matches("http://")
                .trim_end_matches('/')
        }) {
            let sign = if mine
                .iter()
                .any(|(_, v)| e.sign_via_public(&validator_node(&v.name)))
            {
                "Their /v1/sign answers only requests the sequencer signed"
            } else {
                "Their /v1/sign stays private"
            };
            let mut c = format!(
                "# Generated by caravel ([env.{}], host {host}): its validators' public API{}. {sign}.\n{name} {{\n\tencode gzip\n\n",
                m.env_name,
                if web_here { " and the web app" } else { "" }
            );
            for (i, v) in &mine {
                let node = validator_node(&v.name);
                // Its /v1/sign passes only when the sequencer calls it here,
                // and then only signed requests are answered (DEC-095).
                let closed = if e.sign_via_public(&node) {
                    ""
                } else {
                    "\t\trespond /v1/sign 404\n"
                };
                c += &format!(
                    "\thandle_path /validators/{}/* {{\n{closed}\t\treverse_proxy {}:{}\n\t}}\n",
                    v.name,
                    e.listen_on(host, &node),
                    validator_port(m, *i)
                );
            }
            if web_here {
                c += &web_config_route(root);
                if r.web {
                    c += &web_route(root);
                }
            }
            c += "}\n";
            out.insert(caddy, c);
        }
        return out;
    }
    out.insert(
        format!("systemd/{pre}sequencer.service"),
        unit(
            &format!("Caravel sequencer ({net})"),
            "",
            true,
            None,
            &format!("{bin} sequencer --config {root}/config/sequencer.toml"),
            root,
        ),
    );
    out.insert(
        format!("systemd/{pre}validator@.service"),
        unit(
            &format!("Caravel validator %i ({net})"),
            &format!(" {pre}sequencer.service"),
            false,
            None,
            &format!("{bin} validator --config {root}/config/validator-%i.toml"),
            root,
        ),
    );
    out.insert(
        format!("systemd/{pre}relayer.service"),
        unit(
            &format!("Caravel relayer ({net})"),
            &format!(" {pre}sequencer.service"),
            true,
            Some(&format!("{root}/relayer")),
            &format!(
                "/usr/bin/node {root}/relayer/dist/main.js --config {root}/config/relayer.json"
            ),
            root,
        ),
    );
    if let Some(host) = m.env.host.public_url.as_deref().map(|u| {
        u.trim_start_matches("https://")
            .trim_start_matches("http://")
            .trim_end_matches('/')
    }) {
        let mut c = format!(
            "# Generated by caravel ([env.{}]): the lane's public API, each validator's\n# public API{}. The sequencer's /internal/* and the validators' /v1/sign stay private.\n{host} {{\n\tencode gzip\n\n\thandle /internal/* {{\n\t\trespond 404\n\t}}\n\thandle /v1/* {{\n\t\treverse_proxy {}:{}\n\t}}\n",
            m.env_name,
            if r.web { " and the web app" } else { "" },
            e.listen_on(&e.primary_host(), "sequencer"),
            m.env.sequencer.port
        );
        for (i, v) in &mine {
            c += &format!(
                "\thandle_path /validators/{}/* {{\n\t\trespond /v1/sign 404\n\t\treverse_proxy {}:{}\n\t}}\n",
                v.name,
                e.listen_on(&e.primary_host(), &validator_node(&v.name)),
                validator_port(m, *i)
            );
        }
        if web_here {
            c += &web_config_route(root);
        }
        if r.web {
            c += &web_route(root);
        }
        c += "}\n";
        out.insert(caddy, c);
    }
    out
}

/// A YAML string (JSON's quoting, which YAML reads).
fn y(s: &str) -> String {
    serde_json::Value::String(s.to_string()).to_string()
}

/// A docker host's `compose.yml` and, with a public URL, its `Caddyfile`
/// (D-02, DEC-112): one service per node it runs, from the release's images,
/// with the hardening the systemd units have; `web` (Caddy) when it serves
/// the lane's public API or web app. Paths on the left of a mount are the
/// host's root; the containers see `/opt/caravel`.
fn docker_files(
    m: &Manifest,
    r: &Resolved,
    host: &str,
    root: &str,
) -> Result<BTreeMap<String, String>> {
    let e = &m.env;
    let spec = e.host_spec(host);
    let primary = e.primary_host() == host;
    let image = |role: &str| -> Result<String> {
        r.images.get(role).cloned().ok_or_else(|| {
            anyhow::anyhow!(
                "the release has no {role} image: build its images (scripts/build-images.sh) or use a release from CI, which lists them in IMAGES"
            )
        })
    };
    let node_image = image(&format!("{}-node", r.template))?;
    // Where a node's port is published: loopback for this machine's checks,
    // and the private address when another host calls it.
    let ports = |node: &str, port: u16| -> String {
        let mut p = vec![format!("127.0.0.1:{port}:{port}")];
        let reached = if node == "sequencer" {
            e.run_validators()
                .any(|(_, v)| e.host_of(&validator_node(&v.name)) != host)
        } else {
            !primary
        };
        if let (true, Some(a)) = (reached, &spec.private_address) {
            p.push(format!("{a}:{port}:{port}"));
        }
        format!(
            "    ports: [{}]\n",
            p.iter().map(|x| y(x)).collect::<Vec<_>>().join(", ")
        )
    };
    let hardening = |node: &str| {
        format!(
            "    extra_hosts: [\"host.docker.internal:host-gateway\"]\n    user: \"${{CARAVEL_UID:-10001}}:${{CARAVEL_GID:-10001}}\"\n    read_only: true\n    tmpfs: [/tmp]\n    security_opt: [\"no-new-privileges:true\"]\n    cap_drop: [ALL]\n    restart: unless-stopped\n    logging: {{ driver: local, options: {{ max-size: \"10m\", max-file: \"3\" }} }}\n    labels: {{ caravel.lane: {}, caravel.env: {}, caravel.node: {} }}\n",
            y(&m.lane.lane.name),
            y(&m.env_name),
            y(node)
        )
    };
    let config = format!(
        "      - {}\n",
        y(&format!("{root}/config:{RUN_ROOT}/config:ro"))
    );
    let data = format!("      - {}\n", y(&format!("{root}/data:{RUN_ROOT}/data")));
    let key = |name: &str| {
        format!(
            "      - {}\n",
            y(&format!(
                "{root}/keys/{name}.key:{RUN_ROOT}/keys/{name}.key:ro"
            ))
        )
    };
    let env_file = format!("    env_file: [{}]\n", y(&format!("{root}/keys/env")));
    let mut c = format!(
        "# Generated by caravel ([env.{env}], host {host}): the lane's nodes as containers (DEC-112).\n# caravel apply runs it; caravel logs, status and destroy read it.\nname: {name}\nservices:\n",
        env = m.env_name,
        name = y(&spec.compose_project(&m.lane.lane.name, &m.env_name)),
    );
    if primary {
        c += &format!(
            "  sequencer:\n    image: {img}\n    command: [\"sequencer\", \"--config\", {cfg}]\n{env_file}    environment: {{ RUST_LOG: info }}\n    volumes:\n{config}{data}{k}{ports}{h}",
            img = y(&node_image),
            cfg = y(&format!("{RUN_ROOT}/config/sequencer.toml")),
            k = if r.sequencer_key.is_some() { key("sequencer") } else { String::new() },
            ports = ports("sequencer", e.sequencer.port),
            h = hardening("sequencer"),
        );
    }
    for (i, v) in e.run_validators() {
        let node = validator_node(&v.name);
        if e.host_of(&node) != host {
            continue;
        }
        c += &format!(
            "  {node}:\n    image: {img}\n    command: [\"validator\", \"--config\", {cfg}]\n    environment: {{ RUST_LOG: info }}\n    volumes:\n{config}{data}{k}{ports}{dep}{h}",
            img = y(&node_image),
            cfg = y(&format!("{RUN_ROOT}/config/{node}.toml")),
            k = key(&node),
            ports = ports(&node, validator_port(m, i)),
            dep = if primary { "    depends_on: [sequencer]\n" } else { "" },
            h = hardening(&node),
        );
    }
    if primary {
        c += &format!(
            "  relayer:\n    image: {img}\n    command: [\"--config\", {cfg}]\n{env_file}    volumes:\n{config}{data}    depends_on: [sequencer]\n{h}",
            img = y(&image("relayer")?),
            cfg = y(&format!("{RUN_ROOT}/config/relayer.json")),
            h = hardening("relayer"),
        );
    }
    let mut out = BTreeMap::new();
    let web_here = e.web_host().as_deref() == Some(host);
    if let Some(site) = spec.public_url.as_deref().map(|u| {
        u.trim_start_matches("https://")
            .trim_start_matches("http://")
            .trim_end_matches('/')
            .to_string()
    }) {
        // The app is served where [web] puts it, or beside the sequencer's
        // API when there is no [web] (as on systemd hosts).
        let serve_app = r.web && (web_here || (primary && e.web.is_none()));
        let web_image = match (serve_app, r.images.get(&format!("{}-web", r.template))) {
            (true, Some(i)) => i.clone(),
            _ => image("caddy")?,
        };
        c += &format!(
            "  web:\n    image: {img}\n    ports: [\"80:80\", \"443:443\", \"443:443/udp\"]\n    volumes:\n      - {cf}\n{config}      - {cd}\n      - {cc}\n    read_only: true\n    tmpfs: [/tmp]\n    security_opt: [\"no-new-privileges:true\"]\n    cap_drop: [ALL]\n    cap_add: [NET_BIND_SERVICE]\n    restart: unless-stopped\n    logging: {{ driver: local, options: {{ max-size: \"10m\", max-file: \"3\" }} }}\n    labels: {{ caravel.lane: {lane}, caravel.env: {env}, caravel.node: \"web\" }}\n",
            img = y(&web_image),
            cf = y(&format!("{root}/config/Caddyfile:/etc/caddy/Caddyfile:ro")),
            cd = y(&format!("{root}/caddy/data:/data")),
            cc = y(&format!("{root}/caddy/config:/config")),
            lane = y(&m.lane.lane.name),
            env = y(&m.env_name),
        );
        let mut f = format!(
            "# Generated by caravel ([env.{}], host {host}): the lane's public API{}, served by its web container.\n{site} {{\n\tencode gzip\n\n",
            m.env_name,
            if serve_app { " and the web app" } else { "" },
        );
        if primary {
            f += &format!(
                "\thandle /internal/* {{\n\t\trespond 404\n\t}}\n\thandle /v1/* {{\n\t\treverse_proxy sequencer:{}\n\t}}\n",
                e.sequencer.port
            );
        }
        for (i, v) in e.run_validators() {
            let node = validator_node(&v.name);
            if e.host_of(&node) != host {
                continue;
            }
            // Its /v1/sign passes only when the sequencer calls it through
            // this URL, and then only signed requests are answered (DEC-095).
            let closed = if e.sign_via_public(&node) {
                ""
            } else {
                "\t\trespond /v1/sign 404\n"
            };
            f += &format!(
                "\thandle_path /validators/{}/* {{\n{closed}\t\treverse_proxy {node}:{}\n\t}}\n",
                v.name,
                validator_port(m, i)
            );
        }
        if web_here {
            f += &web_config_route(RUN_ROOT);
        }
        if serve_app {
            f += &web_route(RUN_ROOT);
        }
        f += "}\n";
        out.insert("Caddyfile".to_string(), f);
    }
    out.insert("compose.yml".to_string(), c);
    Ok(out)
}

/// Validator `i`'s port (0-based, in file order). The manifest checked it exists.
pub fn validator_port(m: &Manifest, i: usize) -> u16 {
    m.env.validators[i]
        .port(m.env.sequencer.port)
        .expect("validated by the manifest")
}

/// The config files a node reads: the lane file and its own.
pub fn node_files(node: &str) -> [String; 2] {
    let own = match node {
        "sequencer" => "sequencer.toml".to_string(),
        "relayer" => "relayer.json".to_string(),
        v => format!("{v}.toml"),
    };
    ["lane.toml".to_string(), own]
}
