//! The node configs a deployment gives, as files under the host's root:
//!
//! ```text
//! <root>/config/lane.toml            the lane file without [env]
//! <root>/config/sequencer.toml
//! <root>/config/validator-<name>.toml
//! <root>/config/relayer.json
//! <root>/keys/                       validator keys and the env file (never rendered here)
//! <root>/data/                       stores
//! <root>/{bin,contracts,relayer,relayer-feeds}/   the release
//! ```
//!
//! Paths are absolute, so a config means the same thing wherever it is read.
//! No secret is in any of these files: keys are files under `keys/`, and the
//! sequencer and relayer read theirs from the environment.

use std::collections::BTreeMap;

use anyhow::Result;
use serde_json::json;

use crate::address::strkey;
use crate::manifest::Manifest;
use crate::plan::Key;

/// What rendering needs besides the lane file: keys and hashes, resolved.
#[derive(Clone, Debug)]
pub struct Resolved {
    pub template: String,
    pub engine_wasm_hash: Key,
    pub settlement: Key,
    /// Each validator's public key, in file order.
    pub validator_keys: Vec<Key>,
}

pub fn g(k: &Key) -> String {
    stellar_strkey::ed25519::PublicKey(*k)
        .to_string()
        .as_str()
        .to_string()
}

fn hex(k: &[u8]) -> String {
    k.iter().map(|b| format!("{b:02x}")).collect()
}

/// A TOML string literal.
fn q(s: &str) -> String {
    toml::Value::String(s.to_string()).to_string()
}

fn list(items: &[String]) -> String {
    format!(
        "[{}]",
        items.iter().map(|s| q(s)).collect::<Vec<_>>().join(", ")
    )
}

/// `<template>_engine.wasm`, as `scripts/build-contracts.sh` names it.
pub fn engine_file(template: &str) -> String {
    format!("{template}_engine.wasm")
}

/// `validator-<name>`.
pub fn validator_node(name: &str) -> String {
    format!("validator-{name}")
}

/// Every generated file, by its path under `<root>/config/`.
pub fn render(
    m: &Manifest,
    r: &Resolved,
    root: &str,
    epoch: u64,
) -> Result<BTreeMap<String, String>> {
    let e = &m.env;
    let passphrase = e.network.passphrase();
    let settlement = strkey(&r.settlement);
    let engine = format!("{root}/contracts/{}", engine_file(&r.template));
    let engine_hash = hex(&r.engine_wasm_hash);
    let lane = format!("{root}/config/lane.toml");
    let seq_url = format!("http://127.0.0.1:{}", e.sequencer.port);
    let mut out = BTreeMap::new();

    out.insert(
        "lane.toml".to_string(),
        format!(
            "# Generated by caravel from lane {:?}, [env.{}]; the deployment tables are left out.\n{}",
            m.lane.lane.name,
            m.env_name,
            toml::to_string(&m.lane.raw)?
        ),
    );

    let mut seq = format!(
        "# Generated by caravel ([env.{env}]). CARAVEL_INTERNAL_TOKEN comes from the environment.\n\
         [sequencer]\n\
         listen = {listen}\n\
         lane = {lane}\n\
         engine_wasm = {engine}\n\
         engine_wasm_sha256 = {hash}\n\
         db = {db}\n\
         network_passphrase = {pass}\n\
         settlement_contract = {settlement}\n\
         internal_token_env = \"CARAVEL_INTERNAL_TOKEN\"\n\
         executor = \"wasm\"\n\
         production = {production}\n",
        env = m.env_name,
        listen = q(&format!("127.0.0.1:{}", e.sequencer.port)),
        lane = q(&lane),
        engine = q(&engine),
        hash = q(&engine_hash),
        db = q(&format!("{root}/data/sequencer.sqlite")),
        pass = q(passphrase),
        settlement = q(&settlement),
        production = e.sequencer.production,
    );
    if !e.sequencer.cors_origins.is_empty() {
        seq += &format!("cors_origins = {}\n", list(&e.sequencer.cors_origins));
    }
    seq += &format!(
        "\n[signers]\nepoch = {epoch}\nthreshold = {}\nvalidators = [\n",
        e.threshold
    );
    for (i, (v, k)) in e.validators.iter().zip(&r.validator_keys).enumerate() {
        seq += &format!(
            "  {{ url = {}, key = {}, weight = {} }},\n",
            q(&format!("http://127.0.0.1:{}", validator_port(m, i))),
            q(&g(k)),
            v.weight
        );
    }
    seq += "]\n";
    out.insert("sequencer.toml".to_string(), seq);

    for (i, v) in e.validators.iter().enumerate() {
        let node = validator_node(&v.name);
        let mut t = format!(
            "# Generated by caravel ([env.{env}]). The key is in key_file.\n\
             [validator]\n\
             listen = {listen}\n\
             sequencer_url = {seq_url}\n\
             key_file = {key}\n\
             lane = {lane}\n\
             engine_wasm = {engine}\n\
             engine_wasm_sha256 = {hash}\n\
             db = {db}\n\
             network_passphrase = {pass}\n\
             settlement_contract = {settlement}\n\
             rpc_url = {rpc}\n\
             poll_ms = {poll}\n\
             stellar_poll_secs = {stellar}\n",
            env = m.env_name,
            listen = q(&format!("127.0.0.1:{}", validator_port(m, i))),
            seq_url = q(&seq_url),
            key = q(&format!("{root}/keys/{node}.key")),
            lane = q(&lane),
            engine = q(&engine),
            hash = q(&engine_hash),
            db = q(&format!("{root}/data/{node}.sqlite")),
            pass = q(passphrase),
            settlement = q(&settlement),
            rpc = q(m.rpc_url()),
            poll = e.validator_polling.sequencer_ms,
            stellar = e.validator_polling.stellar_secs,
        );
        if !e.sequencer.cors_origins.is_empty() {
            t += &format!("cors_origins = {}\n", list(&e.sequencer.cors_origins));
        }
        out.insert(format!("{node}.toml"), t);
    }

    let feeds: Vec<serde_json::Value> = e
        .relayer
        .feeds
        .iter()
        .map(|f| {
            let mut v = serde_json::to_value(f)?;
            if let Some(module) = v["module"].as_str() {
                if !module.starts_with('/') {
                    v["module"] = json!(format!("{root}/{module}"));
                }
            }
            Ok(v)
        })
        .collect::<Result<_>>()?;
    let mut relayer = json!({
        "rpcUrl": m.rpc_url(),
        "networkPassphrase": passphrase,
        "settlementContract": settlement,
        "sequencerUrl": seq_url,
        "metricsFile": format!("{root}/data/relayer-checkpoints.jsonl"),
        "loops": { "inbox": true, "checkpoints": true },
        "feeds": feeds,
    });
    if let Some(i) = &e.relayer.intervals_ms {
        relayer["intervalsMs"] = serde_json::to_value(i)?;
    }
    out.insert(
        "relayer.json".to_string(),
        serde_json::to_string_pretty(&relayer)? + "\n",
    );
    Ok(out)
}

/// Validator `i`'s port (0-based, in file order). The manifest checked it exists.
pub fn validator_port(m: &Manifest, i: usize) -> u16 {
    m.env.validators[i]
        .port(m.env.sequencer.port)
        .expect("validated by the manifest")
}

/// The config files a node reads: the lane file and its own.
pub fn node_files(node: &str) -> [String; 2] {
    let own = match node {
        "sequencer" => "sequencer.toml".to_string(),
        "relayer" => "relayer.json".to_string(),
        v => format!("{v}.toml"),
    };
    ["lane.toml".to_string(), own]
}
